version: 2

models:
  - name: stg_online_retail_raw
    columns:
      - name: invoice_id
        tests: [not_null]
      - name: ordered_at
        tests: [not_null]
      - name: product_id
      - name: unit_price

  - name: stg_orders
    columns:
      - name: invoice_id
        tests: [not_null, unique]
      - name: ordered_at
        tests: [not_null]

  - name: stg_order_items
    columns:
      - name: invoice_id
        tests: [not_null]
      - name: product_id
        tests: [not_null]
      - name: line_revenue
        tests: [not_null]

  - name: stg_products
    columns:
      - name: product_id
        tests: [not_null, unique]

  - name: stg_customers
    columns:
      - name: customer_id
        tests: [not_null, unique]
