version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: online_retail_raw
        description: "Raw Online Retail transactions loaded from CSV"
        columns:
          - name: invoice_no
          - name: stock_code
          - name: description
          - name: quantity
          - name: invoice_date
          - name: unit_price
          - name: customer_id
          - name: country
